### ISSUE TITLE
Theme the encoding context menu

### ISSUE THREAD

**Issue by madskristensen** [madskristensen/DocumentMargin#1]
The context menu used by [EncodingMargin.cs](https://github.com/madskristensen/DocumentMargin/blob/master/src/Margins/EncodingMargin.cs#L32) isn't themed and looks like this:

![image](https://github.com/madskristensen/DocumentMargin/assets/1258877/b5cb1c5c-510b-4320-b1d2-b0f62b73e4ad)

Using the Toolkit helper `Themes.SetUseVsTheme(ContextMenu, true);` helps a little bit, but doesn't fully theme the context menu. The menu icon column isn't themed.

![image](https://github.com/madskristensen/DocumentMargin/assets/1258877/3da3b3e7-ca5d-42b5-b8ae-6d31da5a69e8)

@reduckted, any idea?

**Comment by reduckted** [comment]
I'm not sure why the menu isn't themed using the toolkit helpers. I have a feeling that Visual Studio expects all context menus to be defined as menus and commands in a VSCT file, rather than using regular WPF context menus, but that's just a guess.

#2 should fix this.
